# Generated by Django 4.2.1 on 2023-05-17 16:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('7\\d{10}')])),
                ('code', models.CharField(db_index=True, max_length=5)),
                ('tag', models.CharField(db_index=True, max_length=20)),
                ('timezone', models.CharField(help_text='Формат: UCT+01:00', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_start', models.DateTimeField()),
                ('text', models.TextField()),
                ('client_filter', models.CharField(db_index=True, max_length=50)),
                ('dttm_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notice.client')),
                ('mailinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notice.mailinglist')),
            ],
        ),
    ]
